/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    CitationPopover: typeof import('./src/components/report/CitationPopover.vue')['default']
    CitationsPanel: typeof import('./src/components/report/CitationsPanel.vue')['default']
    CommandBar: typeof import('./src/components/layout/CommandBar.vue')['default']
    CostDashboard: typeof import('./src/components/cost/CostDashboard.vue')['default']
    CostSparkline: typeof import('./src/components/cost/CostSparkline.vue')['default']
    EChart: typeof import('./src/components/charts/EChart.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FindingBoard: typeof import('./src/components/task/FindingBoard.vue')['default']
    NewTaskComposer: typeof import('./src/components/task/NewTaskComposer.vue')['default']
    NodeCostBreakdown: typeof import('./src/components/cost/NodeCostBreakdown.vue')['default']
    PermissionQueue: typeof import('./src/components/permission/PermissionQueue.vue')['default']
    PlanReviewPanel: typeof import('./src/components/task/PlanReviewPanel.vue')['default']
    QualityGatePanel: typeof import('./src/components/task/QualityGatePanel.vue')['default']
    ReportRenderer: typeof import('./src/components/report/ReportRenderer.vue')['default']
    ResearchPlanMatrix: typeof import('./src/components/task/ResearchPlanMatrix.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceInspector: typeof import('./src/components/report/SourceInspector.vue')['default']
    TaskTimeline: typeof import('./src/components/task/TaskTimeline.vue')['default']
    WorkflowCanvas: typeof import('./src/components/task/WorkflowCanvas.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
